name: Update Airtable with # Reg/App

on:
  schedule:
    - cron: "0 8 * * *"  # Runs at 8:00 AM every day

jobs:
  update_airtable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Airtable update script
        run: python snapshots.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
